### ISSUE TITLE
Install to both partitions in one call

### ISSUE THREAD

**Issue by Eeems** [FouzR/rM_dualboot#3]
You can mount the second partition temporarily and make the necessary changes to enable the service manually, since it's just adding a file link.

**Comment by FouzR** [comment]
Hmm, mounting seems easy enough, but what of the service file
How would I tell systemd to enable it, unless I dig for the location of the config and manually change it...Let me look into how I could do it

**Comment by Eeems** [comment]
> Hmm, mounting seems easy enough, but what of the service file How would I tell systemd to enable it, unless I dig for the location of the config and manually change it...Let me look into how I could do it

You would need to manually create the symlink that systemctl creates for it. When running `systemctl enable ...` you'll see that it outputs that it creates a symlink. That's what you'd need to do manually.

**Comment by FouzR** [comment]
Solved for the most part in the https://github.com/FouzR/rM_dualboot/tree/Improved branch
Will either merge with main and have the current code in main for a singular partition be it's own branch for people who only want to enable it in the current partition. Might make a 3rd branch for the code to _only_ install to the fallback. Plans for the future I suppose
